name: Deploy
on:
  push:
defaults:
  run:
    shell: bash
env:
  REPO_NAME: ${{github.event.repository.name }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::991009956481:role/GitHubAction-AssumeRoleWithAction
        aws-region: us-east-1

    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9

    - name: Install AWSCLI
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Deploy to S3
      run: |
        aws s3 rm s3://dd-unplugged-website --recursive
        aws s3 sync ./ s3://dd-unplugged-website --exclude ".git*" --exclude "*.md*"
